### PR TITLE
Fix sdist install for python >=3.9

### LINKED ISSUE #25: Installation via PyPi does not work with Python 3.9
When trying to install via `pip install weighted-levenshtein` using Python 3.9 the following error occurs multiple times:

```
weighted_levenshtein\clev.c(20188): error C2039: "tp_print": is not a member of "_typeobject"
D:\...\include\cpython/object.h(193): note: see declaration of '_typeobject'
```

As I read in this [StackOverflow answer](https://stackoverflow.com/a/65465906/6513167), `tp_print` was removed in Python 3.9. (some more details: [here](https://www.python.org/dev/peps/pep-0590/#changes-to-the-pytypeobject-struct))

I am absolutely not familiar with Cython because I have never used it before, however I was able to fix the problem by cloning the project, installing a more recent version of Cython (0.29.24) and simply installed weighted-levenshtein locally with `pip install .`.

So maybe it is enough to increase the version in _requirements.txt_.

### PR DESCRIPTION
**Pull request by JacobHayes**
This removes the `clev.c` file from the sdists, which was generated against an older cython version and references APIs removed in python 3.9. By removing the `.c` file from the dist, a fresh one will be generated for each install for the correct python version (and likely newer cython versions).

I also switched the build requirements over to [PEP 517](https://peps.python.org/pep-0517/), which silences this warning during `python3 setup.py sdist`:
```
SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
```

Closes #25

### CODE REVIEW

**Comment by JacobHayes** [comment]
@pachewise do you think you'd have time to look at this? Thanks!

**Review by pachewise — APPROVED** [review]
Unfortunately, I don't work at InfoScout/Numerator anymore so I won't be able to merge this in. That said, I agree with the changes and it works for me on Python 3.10:

image

**Comment by JacobHayes** [comment]
Thanks @pachewise and sorry to bother you then! Perhaps @infoscoutcorp or @RevolutionTech could take a look if you're still there? 😅

Otherwise, do either of you know anyone still there who might be able to merge and release this? Thanks!

**Comment by RevolutionTech** [comment]
I'm afraid I can't help -- I don't work at InfoScout/Numerator anymore either.
